### PR TITLE
#82 Add support for importing data in COCO format

### PR DESCRIPTION
**Pull request by jbovee**
# Purpose / Goal
Add support for importing COCO formatted files/data

Related to #82 

# Type
Please mention the type of PR

* [ ] Bug Fix
* [ ] Refactoring / Technology upgrade
* [x] New Feature
* [ ] Documentation
* [ ] Other : | Please Specify |

**Note** : Please ensure that you've read contribution [guidelines](CONTRIBUTING.md) before raising this PR.

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Can you please share a screenshot of a labeled image? before exporting in coco format and after importing the same format. Please remember to reload the application and import the same image for the comparison.

**Comment by jbovee** [comment]
I created a short video and [uploaded it to gfycat](https://giant.gfycat.com/UnluckyFatherlyChrysomelid.webm) of me exporting from an image with shapes, reloading the page, and then loading that same file to the same image.

**Comment by amitguptagwl** [comment]
This is fantastic. Let me review your changes. validate if the format that we export is also compatible with other annotation tools.

**Comment by jbovee** [comment]
Are there any particular tools you'd recommend I test it with?

**Comment by amitguptagwl** [comment]
Thanks for your changes.

**Comment by amitguptagwl** [comment]
Will you mind if I share your video example to inform users about how import/export COCO format works with this application?

**Pull request merged**
