### PR TITLE
Added default zoom level to settings

### LINKED ISSUE #134: Add default zoom level to settings
> open http://imglab.ml/ > Open left top menu > Settings > General tab

We have to add an option in settings to set the default zoom level when an image loads. It should not impact current functionality. Settings should also saved in browser's cache.

> [Watch](https://github.com/NaturalIntelligence/imglab/watchers) for changes, or [Bookmark](https://github.com/NaturalIntelligence/imglab/stargazers) for easy discovery.
> [Fund](https://www.patreon.com/bePatron?u=9531404) this project for new features and maintenance.
> [Showcase] your project with us by raising an issue

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65709796-add-default-zoom-level-to-settings?utm_campaign=plugin&utm_content=tracker%2F76641010&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F76641010&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by iKonstX**
# Purpose / Goal
Please specify here what you're planning to achieve by this pull request and how it can help in regard of this work-space. 
I implemented the default zoom level setting as requested in the linked issue. I also fixed a bug with zoom levels not updating visually when switching between different images. 

Please mention the issue number, if exists.
This closes #134

# Type
Please mention the type of PR

* [X] Bug Fix
* [ ] Refactoring / Technology upgrade
* [X] New Feature
* [ ] Documentation
* [ ] Other : | Please Specify |

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Thanks for your PR. Can you please add a GIF in comment to demonstrate the frontend changes?

**Comment by iKonstX** [comment]
imglabsettings

There you go.

**Comment by amitguptagwl** [comment]
Thanks for sharing the GIF. I'll try your changes locally and then merge it.

**Comment by johachi** [comment]
Could this be merged? I would love it if it was possible to set default zoom level! @amitguptagwl

**Comment by amitguptagwl** [comment]
@johachi not yet. will do on this Sunday.

**Comment by johachi** [comment]
> @johachi not yet. will do on this Sunday.

Just sending a friendly ping!

**Comment by amitguptagwl** [comment]
Sorry for the delay.. running busy :)

**Comment by johachi** [comment]
Thank you!

**Pull request merged**
