### PR TITLE
Added color picker using Spectrum

### PR DESCRIPTION
**Pull request by alextychan**
# Purpose / Goal
Added a color picker using Spectrum to change feature color points. Once the color is changed, it will be changed globally, meaning that all other points will change to the selected color. This is implemented using a global variable in appConfig.

Issue number #94.

# Type
Please mention the type of PR

* [ ] Bug Fix
* [ ] Refactoring / Technology upgrade
* [x] New Feature
* [ ] Documentation
* [ ] Other : | Please Specify |

**Note** : Please ensure that you've read contribution [guidelines](CONTRIBUTING.md) before raising this PR.

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Thanks for your PR. But, for my understanding, is there any advantage to use any 3rd party library? Can't we use https://www.w3schools.com/colors/colors_picker.asp ?

**Comment by alextychan** [comment]
The only benefit of using this library would be the backward support. 

"input type=color" does not provide support for Safari in accordance to this table. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

But I do agree that using the third party library might be overkill. The file size is pretty huge.

**Comment by alextychan** [comment]
I have changed it to use the native color picker. Please have a look.

**Comment by amitguptagwl** [comment]
Thanks for the changes. I believe (though not completely sure) this application is not compatible with safari. And unfortunately I don't have mac to test it.

**Pull request merged**
