### PR TITLE
Document newly added functionalitities #106

### PR DESCRIPTION
**Pull request by derekdkim**
# Purpose / Goal
This is still a work in progress for issue #106.
Waiting for issue #115 to be resolved.

## Added:
Demo GIF for zoom feature.
Demo GIF for keyboard shortcuts.
Created features.md (only has GIFs with the corresponding feature headings)
Updated README

## To be done:
Demo GIF for the label copy/pasting.
Updating documentation to reflect this change.

# Type

* [ ] Bug Fix
* [ ] Refactoring / Technology upgrade
* [ ] New Feature
* [x] Documentation
* [ ] Other : | Please Specify |

# Concerns:

Issues with some shortcuts.

The following shortcuts do not work / I can't find those tools:
Alt + + (Plus key) : Zoom
Alt + W : Magic wand

The following conflicts with the default hotkey (Edit) on popular browsers (tested on Chrome and Firefox). Perhaps it may be wiser to change to one that isn't used.
Alt + E : Ellipse

Should features.md and README.md essentially contain the same information or did you have something else in mind? I could either:

1) Redirect the user from the README to the features doc with a simple link.
2) Show GIFs in the README then add some description for every feature in the features doc.
3) Have README and features contain the exact same information.

### CODE REVIEW

**Comment by amitguptagwl** [comment]
@derekdkim Thanks for raising your concerns. Here are my comments

> Alt + + (Plus key) : Zoom

Functionality is present, linking is rest. #107 

> Alt + W : Magic wand

It can be commented if present or left if raise no issue. #64

> The following conflicts with the default hotkey (Edit) on popular browsers.. 

This issue presents with other tools as well. Because the hotkeys start with *Alt* key are generally associated to open browser's menu or to invoke particular plugin. Hotkeys start with *Ctrl* key are generally associated with a webpage's oprations like copy, paste, select all etc. So, I believe, we'll have to review all the shortcuts and assign them with key-mapping which can work with all the browsers, eg "w" without *Alt* key to select magic wand. In this case, we'll have to take care that such events should not be triggered when we're working on text boxes.

> Should features.md and README.md essentially contain the same information or did ...

README.md may contain GIF for main features (2 to 3 maximum) and link for others pointing to features.md. Because;

1. Due to the size of the GIFs, README.md will become heavy to load.
2. Due to the number of increasing features, README.md will become lengthy to read.

**Comment by amitguptagwl** [comment]
My suggestions on generating GIFs

1. Keep their size as minimum as possible (max 2.5 mb). For this, combine multiple features in single GIF until or unless it becomes complex and confusing. A simple rule for this is, a GIF should have one main feature and some small features. 
2. Speed up the animation so that it can be finished in less time. People generally get bored with long tutorials.
3. Cut the unnecessary part, long pauses, or repeated actions / information.

**Comment by amitguptagwl** [comment]
No problem. You can probably share some here along with size before updating PR.

**Comment by derekdkim** [comment]
I made an [Imgur Album](https://imgur.com/a/dyYCtHL) so you guys can check it out and give me the okay before I commit them in. I got the sizes down but I'm not really sure about adding multiple features in one gif.

**Comment by amitguptagwl** [comment]
LFTM;

**Comment by amitguptagwl** [comment]
@derekdkim Can you please update the PR with GIF you shared in the last comment?

**Comment by derekdkim** [comment]
Done. Sorry, I didn't think the PR was going to be merged until everything was done so I didn't do it right away.

**Comment by amitguptagwl** [comment]
We can work on the rest part once the relevant issues are done. I hope, we'll keep adding the features and their documentation.

**Pull request merged**
