### PR TITLE
minified fontello.css

### PR DESCRIPTION
**Pull request by bhavayAnand9**
# Purpose / Goal
This PR is in response to issue #93 

# Type
Code Formatting

### CODE REVIEW

**Comment by amitguptagwl** [comment]
@alexlee-dev You should keep the original file there and should create minified file in addition. Name it as "fontello.min.css". I hope you understand why am I asking you to do this change.

**Comment by bhavayAnand9** [comment]
I'm closing this pull request and will create a new one with above said changes to create new file fontello.min.css with no changes to fontello.css

**Comment by amitguptagwl** [comment]
Sorry @alexlee-dev I didn't carefully read who have raised the PR. @bhavayAnand9 You have missed to refer minified file in index.html.

**Comment by bhavayAnand9** [comment]
silly me. Just did that.

**Comment by amitguptagwl** [comment]
Thanks for your PR

**Pull request merged**
