### PR TITLE
#106 Formatting fixes

### PR DESCRIPTION
**Pull request by derekdkim**
# Purpose / Goal

A fix for some formatting issues introduced in the [previous PR](https://github.com/NaturalIntelligence/imglab/pull/117). Sorry about the sloppy job last time.

- Resized gifs to 800x450 to match all other demo gifs.
- Changed relative links to make them work.
- Added a link to features.md on README.md.
- Added an unordered list for the list of keyboard shortcut documentation in README.md.

# Type

* [x] Bug Fix
* [ ] Refactoring / Technology upgrade
* [ ] New Feature
* [x] Documentation
* [ ] Other : | Please Specify |

### CODE REVIEW

**Comment by amitguptagwl** [comment]
I was wondering if we should move How to use guide to some other page like: GUIDE.md or separate page for each guide. And link the topics on README.md. Eg

## How to use
* [Shapes](): creating rectangle (boundary box), circle, polygon. copy-paste.
* [Landmark points](): adding, deleting, labeling, ordering, positioning, style, and ...
* [Keyboard shortcuts](GUIDE.md#keyboard-shortcuts) to speed up your work
* [Using Face plus plus plugin]() for one click annotation
* [Debug for errors]() before reporintg the issue
* [Import/Export]() labelled data. And detail about what information you loose when you save data in particular format.
* [Offline instalation]()
* [Other](): Zoom in/out, torch

**Comment by derekdkim** [comment]
@amitguptagwl I personally feel that most of these demo GIFs would be best served in the features tab (right before other features, as most of these are core features of the app), and each heading can be a link for more information. Some of the smaller features could still have a link but no GIF on the README if it's a smaller feature. That way, how to use can be limited to keyboard shortcuts for convenience and link to the guide and tutorial video for more complicated operations.

**Comment by derekdkim** [comment]
I made a mock-up based on your suggestions. I used anchor tags to link to different tabs in guide and it sort of like an all-in-one user guide. I've only added some of the features that I'm familiar with. The order of the content presented in the guide could also be changed around to make it more intuitive if you were to read it from top to bottom. It's currently pushed onto my test branch.

https://github.com/derekdkim/imglab/tree/test

Let me know what you think.

**Comment by amitguptagwl** [comment]
It looks perfect. Though some additions are required, they can be added later.

**Comment by derekdkim** [comment]
Sorry, I was rebasing my fork and it somehow came into the PR.

**Comment by amitguptagwl** [comment]
Thanks for your effort. I believe you've become the 3rd highest contributor to this app.

**Pull request merged**
