### PR TITLE
Linted Code and Removed Tracking Lines From Workarea

### PR DESCRIPTION
**Pull request by alextychan**
# Purpose / Goal
Linted code and removed tracking lines from workarea.

# Type
Please mention the type of PR
* [ ] Bug Fix
* [x] Refactoring / Technology upgrade
* [ ] New Feature
* [ ] Documentation
* [ ] Other : | Please Specify |

### CODE REVIEW

**Comment by amitguptagwl** [comment]
tracking lines are required. I'm considering that this commit is not to remove the feature.

**Comment by alextychan** [comment]
I've moved tracking lines into the side of the tool bar, because the tracking line affect the performance of the application due to the constant rerendering of the position indicator.

**Comment by amitguptagwl** [comment]
Tracking lines were not being used to display the mouse coordinates. Both have a different purpose. Tracking lines help to select the right point to start, especially in the case of rectangles.

**Comment by alextychan** [comment]
Hmm. When the shapes are selected, svg.js would show the surrounding points of the shape. Those points can then be interacted with. 

So I am not sure why there's a need for tracking lines. Under what use case would it be useful?

**Comment by amitguptagwl** [comment]
There are 2 aspects;

1. draw the rectangle then select the move tool to adjust start points. Then stretch it to properly cover the object

without tracking lines


2. start drawing the rectangle from the right point with the help of tracking lines.

with tracking lines

**Comment by alextychan** [comment]
Both the examples above already work without the tracking lines. I think it's more consistent to just allow users to plot it using mouse clicks as the tracking lines don't provide additional merit. If you would still prefer there to be tracking lines then I'll add it back to the project.

**Comment by amitguptagwl** [comment]
Tracking lines are required to improve the user experience not to complete some functionality.

However, we can take the decision to provide a toggle button to enable/disable them on demand.

**Pull request merged**
