### PR TITLE
added tool bar

### PR DESCRIPTION
**Pull request by malfple**
# Purpose / Goal

Issue
#17 

I created a new file toolbox.js, can always combine/change the file name :stuck_out_tongue: 
Commented out the toggle button.
Added tool bar.
At the moment, I put the tool bar at the left panel above the Box/Point Detail. It is still in the form of text buttons.
The buttons will be disabled if it is current tool selected (I don't know if it is good).
I moved some stuffs related to dragging or showing/hiding the empty button whatever from uiaction.js to toolbox.js, which could be reverted if wanted.

Learnt jQuery along the way :stuck_out_tongue: 

# Type

[ ] Bug Fix

[ ] Refactoring / Technology upgrade

[x] New Feature

[ ] Documentation

[ ] Other : | Please Specify |

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Thanks for the changes. It'is well implemented. Can we do some more changes, like

Don't display "some random tool" button until it is implemented. Or the better approach can be to create a tool class with what possible actions it can have. Then we can create a class, say toolbox, containing  list of tools available (I'll say number of instances of tool class). There can be a method "select" which will load relevant actions in action bar.

Let's modify the CSS to display tools one in a line. Tool class can also have properties like icon and label.

It may increase the complexity of implementation. But I believe you'll enjoy that.

**Comment by amitguptagwl** [comment]
In addition of above comment, we should also remove the switch library, as it is not required anymore.

**Comment by malfple** [comment]
@amitguptagwl Hi! I tried removing bootstrap-switch.min.js and .min.css, but there seem to be an error in jquery.min.js, can I get directions how to remove it properly?

**Comment by amitguptagwl** [comment]
@malfple check #15 . I've done some UI changes with riotjs on other branch [riot](http://htmlpreview.github.io/?https://github.com/NaturalIntelligence/imglab/blob/riot/index.1.html). I believe riot will be new for you. But it is worth to check. Tomorrow I'll work on creating label.

**Comment by malfple** [comment]
@amitguptagwl Hi! I'm a little bit confused. Should I complete the toolba with the additional changes you suggested, or should I wait for the riotjs version to complete?

**Comment by amitguptagwl** [comment]
@malfple sorry for the delay. But it's good to wait. I believe riot version can solve the issue gracefully.

Update: I've created riot gallery, and toolbar. I'm working on creating label when a tool is selected. I'm taking SVG elements for drawing.

I've created separate repo [riot-svg](https://github.com/NaturalIntelligence/riot-svg). It can be good for learning. So have a look.

**Comment by amitguptagwl** [comment]
@malfple Sorry for the delay. I've completed rectangle part and submitted the code of **riot-svg** for code review.  I've found some issues with riot js library in case of creating a shape using mouse event.

From the prospective of this issue, as I've already added the ToolBar in the new design. So if you want you can ignore my further messages.

**Comment by malfple** [comment]
I see. So, should this pr be closed?

**Pull request closed without merging**
