### PR TITLE
riot mount method call change

### PR DESCRIPTION
**Pull request by prithvihv**
# Purpose / Goal
issue #92
refactored code to call the method with only 1 parameter , also used a simple http server to test changes everything seems fine 

# Type
Please mention the type of PR

* [ ] Bug Fix
* [ ] Refactoring / Technology upgrade
* [ ] New Feature
* [ ] Documentation
* [x] Refactor

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Have you tested the application? It looks like you've done the changes in the call but no change in workarea.tag.html

**Comment by prithvihv** [comment]
alright i think i updated that :+1:

**Comment by amitguptagwl** [comment]
Thanks. Have you tested the application after your changes?

**Comment by prithvihv** [comment]
i used the app and all the function seemed to be working as before , im not familiar with how riot works . Any thing specific i need to test ? 
Thank you

**Comment by amitguptagwl** [comment]
Just import 2-3 images, draw some shapes. Move to another image draw some shapes. Again come back to previous image and see if you can see all previous shapes you drawn. Please also check browser console (F12) for any error.

**Comment by prithvihv** [comment]
Hey amit , 
i did that the shapes were still there and no errors  :smiley:

**Comment by amitguptagwl** [comment]
Grt and thanks for the PR.

**Pull request merged**
