### PR TITLE
Porting over from Riot.js to Vue.js [WIP]

### PR DESCRIPTION
**Pull request by alextychan**
# Purpose / Goal
Porting over tech stack from Riot.js to Vue.js. As mentioned in #10. I won't be able to work on this actively for a while. So I'm leaving this here. Anybody who's adventurous enough can pick it up. 

# Type
Please mention the type of PR
* [ ] Bug Fix
* [x] Refactoring / Technology upgrade
* [ ] New Feature
* [ ] Documentation
* [ ] Other : | Please Specify |

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Please also check that Google Analytics is working fine.

**Comment by alextychan** [comment]
Please have a look and merge it into the Vue branch so that future pull requests may reference it.

**Comment by amitguptagwl** [comment]
It is a big change, it'll take time to review. So I'll probably merge to vue branch first.

>  Google tags aren't implemented as of yet. I've left the things that still need to be implemented in a roadmap.txt file.

I want you to add it in your speclist.

Questions:
*  What does roadmap.txt contain? rest features or all targeted features? Better if you create a roadmap.md > create a checklist of what has to be done > checks what is already done. So I'll add more points if there is something missing. Also add testscenarios.md. So we can add necessary features to test.
* What is your current plan? I can see you've removed many important files including CNAME, and documentation.

**Comment by alextychan** [comment]
I will do so at my earliest convenience.

**Comment by amitguptagwl** [comment]
I mean any purpose of deleting those files. Were you planning to move them on the different location? rename them? or add later?

**Comment by alextychan** [comment]
I started the project from scratch using the vue-cli. That's why none of the old files exist. The project structure has changed significantly so some of the documentation are out of date. 

Roadmap contains features that aren't implemented. I'll work on the checklist once I have the time as I will be busy this week. Same goes for the docunentation. 

As for the cname, it should be set up on the domain management site?

Since this is still in development we can leave it as is. Run the following command after forking to test out the code locally.
```
npm install
npm run serve
```

**Comment by amitguptagwl** [comment]
now it's clear. CNAME is required for a custom domain for github hosted web pages. Thanks

**Pull request merged**
