### PR TITLE
Discontinue with v1 #88

### PR DESCRIPTION
**Pull request by derekdkim**
# Changes made for Issue #88:

Updated README: Fixed a few typos and awkward phrases, wrote that the legacy version of imglab has been deleted. Since the downloads folder no longer exists and the link returns 404 error, I removed that line as well.

Files only used in old.html:

css/bootstrap-switch.min.css
css/font-awesome.min.css
css/slider.css
css/slider.1.css
css/tags.css
js/thirdparty/bootstrap-switch.min.js
js/thirdparty/jsplumb.min.js

js/fileOperation.js
js/uiaction.js
js/widget.js
js/FaceBox.js
js/labels.js
js/labelFileLoader.js
js/dataloader.js
js/slider.js
js/Face++DataParser.js
js/dlibDataHandler.js

Images only used in old.html:

img/githubribon.png -- Fork me on GitHub

CSS affecting old.html elements:

style.css:

.facebox
.ptn
.sidebar
#img_home
#actualData
#img_overlay
#ptnDtl, #boxDtl

# Type:

* [ ] Bug Fix
* [x] Refactoring / Technology upgrade
* [ ] New Feature
* [x] Documentation
* [ ] Other : | Please Specify |

# Concerns:

Sidebar hidden on Chrome and IE (works fine on Firefox and Edge). Unchanged clone from master branch also has this problem. **(Fixed and added documentation in technical.md)**

Potentially unused JS methods inside files that are currently in use by both index.html and old.html.

### CODE REVIEW

**Comment by alextychan** [comment]
@derekdkim, I have looked at the problem and have found that it's due to the riot.js compiler using AJAX to fetch the tags. 

When you view html files locally, it's under the protocol scheme: file://. Chrome prevents any CORS requests from running when under that protocol by default. Hence one way of going around it is to start a local server. Please have a look at https://github.com/riot/riot/issues/1991.

It would be of great help if you could add documentation for that as well.

**Comment by alextychan** [comment]
On a side note, @derekdkim, it would be best if you create a new branch to work on issues in the future and not work on the master branch directly. Please have a look at the links below.

1. https://softwareengineering.stackexchange.com/questions/335654/git-what-issues-arise-from-working-directly-on-master
2. https://stackoverflow.com/questions/5713563/reasons-for-not-working-on-the-master-branch-in-git

**Comment by alextychan** [comment]
@amitguptagwl, please have a look.

**Comment by alextychan** [comment]
@derekdkim, no worries, it's just a workflow recommendation. Btw, you should definitely sign up for Hacktoberfest. You might win yourself a cool new T-shirt and some stickers. 

Check it out here. https://hacktoberfest.digitalocean.com/

**Comment by amitguptagwl** [comment]
LFTM;
Thanks @derekdkim  for the PR and @alextychan for detail review.

**Pull request merged**
