### PR TITLE
Fix for Issue #31: Show mouse tracking line in v2

### PR DESCRIPTION
**Pull request by rohitkrishna094**
# Purpose / Goal

Fix for Issue #31 - Show mouse tracking line in v2.

# Type
Please mention the type of PR

[X] Bug Fix

[ ] Refactoring / Technology upgrade

[ ] New Feature

[ ] Documentation

[ ] Other : | Please Specify |

Note: Please review and let me know if the changes are good. First PR so hope it goes in. Thanks.

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Just to save time.. Have you tested the application and checked for console errors?

* [ ] upload few images.
* [ ] draw some shapes
* [ ] draw point on the shapes
* [ ] drag and resize shapes
* [ ] load an image bigger than canvas size
* [ ] click on some other images in thumbnail slide bar and come back to image to see if everything is working fine.

**Comment by rohitkrishna094** [comment]
Yes I checked the functionality you mentioned. It works just as it did in v1. Although there is one problem in  v1 as well i.e.,  when a bigger image is loaded and we scroll, the lines are not shown. So in that sense, I guess the issue is not fixed yet. I can try looking into it.

But as of now, it works just like v1. If you are happy with that, let me know. Thanks

**Comment by amitguptagwl** [comment]
We're trying to mimic the functionalities of v1 not the bugs :rofl: . we need to fix that. You can just set width and height using `{opts.img.size.width}`. And keep changing top,left position on mouse move.

Moreover, try to keep the code separate from existing code so that it can be treated as component
Eg
```html
<trackinglines>
   <div id="tracking_v_line" style="height:{opts.img.size.height};"></div>
   <div id="tracking_h_line" style="width:{opts.img.size.width};"></div> 
   <script>
      //set top,left as per mouse coordinates
   </script>
</trackinglines>
```

Similarly create a js function getMouseCoordinates(offset) which can be used in both components.

Points to note
1. DRY: Don't repeat yourself
2. Make the code moduler, reusable, and less cohesive

**Comment by rohitkrishna094** [comment]
Umm, that makes sense. I have a few questions now.

1. How is opt getting passed around tags/[file].html files?
2. If we define trackinglines, should we create another file called tags/trackinglines.tag.html and reference it in v2.html? If so how would I access canvas variable inside trackinglines' script tag? I believe canvas variable which is inside workarea.tag.html would now be out of scope in this new tags/trackinglines.tag.html. 
3. Now the created getMouseCoordinates function goes inside workarea or this new trackinglines file? Or are you maintaining some other file for all utility functions.

Thanks.

**Comment by amitguptagwl** [comment]
@rohitkrishna094 how is going on? seems difficult?

**Comment by rohitkrishna094** [comment]
I have changed/added these files: 

1. tags/trackinglines.tag.html : Created a new file which handles mouse tracking UI component [Major change]
2. js/app.js : Added getCoordinates function here so that its modular and can be reused [Minor Change]
3. tags/workarea.tag.html: Added/referenced trackinglines riot component [Minor Change]
4. v2.html: referenced trackinglines riot tag in the main html [Minor Change]

As of now, I've restructured the code to
1. be modular and have component based structure and
2. work as it did in version 1.

However the issue that I previously mentioned still exists. The issue where if you load a larger image, the tracking lines are not shown completely. Let me try thinking about this issue. If you have any ideas, I'd love to hear them.

**Comment by amitguptagwl** [comment]
First of all I would like to appreciate your effort. I hope you must be learning new things.

Now on the height width issue of tracking lines, it can occur only when values passed to the tag are incorrect; So try this change

```html
<trackinglines width={opts.img.size.width} height={opts.img.size.height}></trackinglines>
```

Remove CSS style

```html
<trackinglines>
   
    <div id="v_line" style="height: {opts.height};" ></div>
    <div id="h_line" style="width: {opts.width};"></div>

:
```

**Comment by rohitkrishna094** [comment]
I tried removing the CSS style and passing width/height arguments to trackinglines tag. But the problem still persists. Look at the image below.

untitled

The part where the green arrow is pointing is missing when I say scroll to right. Same thing happens when I scroll downwards. I believe the values of height/width of the div are out of sync after scrolling. If there is way to get width/height irrespective of scroll, I guess that would work. Same thing happens in version 1 as well. Maybe we can add a new invisible div(set to have absolute coordinates) and then calculate the height and width of red/yellow lines.

**Comment by amitguptagwl** [comment]
Let me merge the code and check where is the issue.

**Comment by amitguptagwl** [comment]
There was a very small issue. Hint: You're not setting color to h_line, v_line in your change then how do they come? :D

I'll really suggest you to join [team](https://github.com/socialat/team) as a developer.

**Pull request merged**
