### PR TITLE
Implemented function to update the suggestecategories variable

### PR DESCRIPTION
**Pull request by beckstev**
# Purpose / Goal
Added a function to update the `suggested_categories` variable, which is required due to the fact that imglab can otherwise only display [default categeories](https://github.com/beckstev/imglab/blob/c19e9c72e65ff01872d63d5b0a39bc99d66a9c34/js/config.js#L167) such as "dog" or "car".

# Type
* [ ] Bug Fix
* [ ] Refactoring / Technology upgrade
* [x] New Feature
* [ ] Documentation
* [ ] Other : | Please Specify |

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Thanks for raising this PR. Can you please add a gif or video highlighting UI changes?

**Comment by beckstev** [comment]
Actually, I opened this pull by mistake. I wanted to merge into my local master. 
However, if you think this a interesting feature I could provide a gif/image. 
In addition, I implemented two features which enhances the functionality of reading json files. 
First, the json file can contain a 'label/text', which can be displayed  in the `Label name` text field.
Second, the json file can include the style of every bbox.

**Comment by amitguptagwl** [comment]
Please include the gif/video. We'll check if that feature doesn't conflict with any planned feature. Then probably we can merge those changes to this repo.

Please raise another PR for your other changes. we'll check if they can be merged straight forward or if they need change/discussion.

**Comment by beckstev** [comment]
I will close this PR because I do not have enough time to prepare a sufficent example.

**Comment by franciscorba** [comment]
Sad this feature is really needed

**Pull request closed without merging**
