### PR TITLE
LabellingData is now saved on and retrieved from localStorage

### PR DESCRIPTION
**Pull request by LandoLucas**
# Purpose / Goal
Resolve issue: https://github.com/NaturalIntelligence/imglab/issues/37

The labellingData object will be saved to the browser localStorage every 5 seconds.
When the application loads, it will try to retrieve the saved data if it exists and use it.

# Type

* [ ] Bug Fix
* [ ] Refactoring / Technology upgrade
* [X ] New Feature
* [ ] Documentation
* [ ] Other : | Please Specify |

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Though the code seems perfect. Can you please confirm that you've tested it for following points?

* Images imported first time
* More images are added
[application reopen]
* some old and new images are imported

Please also check console for any error on chrome and firefox.

**Comment by LandoLucas** [comment]
Yes, I tested all those scenarios and it's behaving correctly.

**Comment by amitguptagwl** [comment]
Thanks for your PR. I would like to appreciate your work.

**Comment by LandoLucas** [comment]
I'll take a look at that error

**Comment by amitguptagwl** [comment]
It's minor. I've fixed that. I'll push the changes. So don't worry.

**Pull request merged**
