### PR TITLE
Modify 'Save' button functionality to save nimn format instead of json format

### PR DESCRIPTION
**Pull request by lopezjorge1**
# Purpose / Goal
I modified the functionality of the save button so that it saves data in nimn format instead of json format. (#23) The next step after this would be to be to modify the 'Browse' button functionality to import data in the nimn format instead of json format.

# Type
Please mention the type of PR

[ ] Bug Fix

[X] Refactoring / Technology upgrade

[ ] New Feature

[ ] Documentation

[ ] Other : | Please Specify |

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Sorry @lopezjorge1 I'm confused with your statement. Do you want to say "I've modified save button functionality to save nimn format instead of json. "Browse" button to import json is rest to modify to import nimn format"

**Comment by lopezjorge1** [comment]
@amitguptagwl I'm sorry for the confusion, but yes that's exactly what I meant.

**Comment by amitguptagwl** [comment]
The important thing that we've to kept in mind while doing any development

* Either we're doing development on other branch than master. Eg I'm working on riot branch now a days to renovate imglab with new UI and tools
* Or the current chanes are not breaking user experience

In your change when you save data in nimn format but don't let user open nimn file then they'll not be able to use their previous work. So let's implement both functions together.

**Comment by lopezjorge1** [comment]
Alright awesome. I was just going to modify the browse button.

**Comment by amitguptagwl** [comment]
I'll try to publish my changes ASAP

**Comment by amitguptagwl** [comment]
I'm done with initial changes in [v2](https://naturalintelligence.github.io/imglab/v2.html). The proposed new data structure is given in store.js. But I've to do some changes in nimn.js. I'll confirm you as soon as I'm done with change in nimn.js.

Thanks for your patience.

**Comment by amitguptagwl** [comment]
changes in nimn.js are done. Now we can go ahead with this PR. But v2.html only. Because new format has many other fields as well.

**Comment by amitguptagwl** [comment]
Done

**Pull request closed without merging**
